# Some instructions of how to interact with the Brewfile
# https://gist.github.com/ChristopherA/a579274536aab36ea9966f301ff14f3f
# 
# A big list of comonly used brew packages
# https://github.com/joelparkerhenderson/brewfile/blob/master/Brewfile

# TODO: migrate it all on Nix and leave here only what cannot be installed through Nix

# Brew aliases functionality
tap "homebrew/aliases"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
# Brew casks extended ability
tap "homebrew/cask-versions"
# Yubikey manager, etc.
tap "homebrew/cask-drivers"
tap "homebrew/core"
# PDR and other docs reader
tap "zegervdv/zathura"
# Rust implementation of `age`
tap "str4d.xyz/rage", "https://str4d.xyz/rage"

# FUSE implementations
tap "macos-fuse-t/homebrew-cask"
brew "fuse-t"
# More of a deprecated one since macOS 12.3 (https://docs.cryptomator.org/en/1.7/desktop/volume-type/#macfuse)
cask "macfuse"

brew "antigen"
brew "avifquicklook"
brew "awscli"
brew "axel"
brew "bat"
brew "bitwarden-cli"
brew "cheat"
brew "circleci"
brew "clang-format"
brew "coreutils"

# wget is not present on every OS, so better stick to curl
# brew "wget"
brew "curl"

brew "direnv"
brew "eksctl"
# Reads/modifies EXIF and video metadata
brew "exiftool"
brew "ffmpeg"
brew "findutils"
brew "fnm"
brew "fzf"
brew "gawk"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "git-absorb"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "gotop"
brew "grc"

# Heroku - in case we want to deploy using the heroku-cli
# tap "heroku/brew"
# brew "heroku"

brew "htop"
brew "i2p"
brew "imagemagick"
# ftp, telnet, etc.
brew "inetutils"
brew "jc"
# Converts output of unix commands to JSON
# https://github.com/kellyjonbrazil/jc
brew "jq"
brew "jupyterlab"
brew "lazydocker"
brew "lazygit"
# VimTeX uses latexmk as the default compiler backend
# latexmk is getting bundled with texlive
# https://mg.readthedocs.io/latexmk.html#installation
brew "texlive"
# Backend processor for BibLaTeX
brew "biber"
# PostgreSQl
brew "libpq"
brew "lsyncd"
brew "lua"
brew "luarocks" # lua package manager
brew "luajit-openresty"
brew "make"
brew "mas"
brew "midnight-commander"
brew "mobile-shell"
brew "mpv"
# Replaces a built-in MacOS version of ncurses for the sake of having an up-to-date terminfo
brew "ncurses"
brew "neofetch"

brew "neovim"
# brew "ranger" # File browser, superseded by nvim
# Is required to fix the ranger's freezes
# https://github.com/ranger/ranger/issues/1787#issuecomment-691528698https://github.com/ranger/ranger/issues/1787#issuecomment-691528698
# brew "highlight"

brew "nginx"
brew "onefetch"
brew "openjdk"
# Mainly for PostgreSQl 
brew "openssl"
# Make SSH up to date
brew "openssh"
# Same as pinentry for GPG, but for SSH
brew "theseal/ssh-askpass/ssh-askpass"
brew "openvpn"
brew "perl"
brew "php"
brew "pipenv"
brew "postgresql"
brew "pyenv"
brew "qemu"
brew "rage"
# GNU utility to edit the command lines as they are typed in.
# Was extracted from bash, now used pretty much everywhere the prompt
# exists. zsh uses zle instead.
# $XDG_CONFIG_HOME/readline/inputrc is the config file.
# https://www.youtube.com/watch?v=MxRTh8wlmJk
# https://tiswww.case.edu/php/chet/readline/rltop.html
brew "readline"
# Nice backup tool
brew "restic"
brew "ripgrep"
brew "rsync"
brew "ruby"
brew "sox"
brew "speedtest-cli"
# As education have finished
# brew "spin"
brew "stow"
# Linter for lua (used by nvim)
brew "stylua"
brew "svgo"
# XDG Base Directory spec-compliant Rust tldr implementation
brew "tealdeer"
brew "testdisk" 
brew "tmux"
brew "tmuxinator"
# Using it instead of the rm for soft-deletion
brew "trash"
brew "tree"
brew "ykman"
brew "yq"
brew "eth-p/software/bat-extras"
brew "zathura"
brew "zathura-djvu"
brew "zathura-pdf-poppler"

cask "1password"
cask "adobe-acrobat-reader"
cask "alt-tab"

# As no Android devices at the moment
# cask "android-file-transfer"
# cask "android-platform-tools"
# KDE Connect for Mac (pairs MacOS, iOS, Android and Linux together)
cask "soduto"

cask "anydesk"
cask "appcleaner"
cask "browserstacklocal"
# Hold the command key a bit longer to get a list of all active shortcuts of the current application
cask "cheatsheet"
cask "cloudflare-warp"
cask "crossover"
cask "dash"
cask "deluge"
cask "devtoys"
cask "discord"
cask "dotnet-sdk"
cask "djview"
cask "docker"
# Nicest diagramming/drawing app
cask "drawio"
cask "duplicati"
cask "element"
cask "fbreader"
cask "figma"
cask "flash-npapi"

# Nerd fonts for the powerlevel10k and vim-airline
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-sauce-code-pro-nerd-font"
# Free font builder
cask "birdfont"

cask "inkscape"
cask "gimp"
cask "gog-galaxy"
cask "gnucash"

# Grammar checking tools
brew "languagetool"
cask "languagetool"
# cask "grammarly"

cask "hazeover"
cask "karabiner-elements"
cask "keycastr"

# Best archiving tool so far
cask "keka"
# Is payed + has annoying paywall notifications
# cask "betterzip"

# Window managers
# cask "amethyst" # superseded by yabai & skhd + is a bit more buggy than the latter combo
# These two work together, one for window management, another for keyboard shortcuts
tap "koekeishiya/formulae"
brew "yabai"
brew "skhd"

# Browsers
cask "chromium"
cask "google-chrome"
cask "microsoft-edge"
cask "firefox"
cask "brave-browser"
cask "tor-browser"
# Browsers managers
mas "Velja", id: 1607635845
# cask "browserosaurus"

# Sindre Sorhus apps (https://sindresorhus.com/)
mas "Hyperduck", id: 2145267525

# The only feature-rich terminal emulator for MacOS with blur background/ligatures is iTerm2
cask "iterm2"
# cask "alacritty"
# cask "kitty"

# The best launchd/ctl inspector/editor
cask "launchcontrol"
# A convenient wrapper around launchctl
# brew "lunchy"

cask "lantern"
cask "mendeley"

# Objective-See (objective-see.org) security-related apps
# Nice and open-source outbound firewall
cask "lulu"
# Prevents "evil-maid" attacks (listens to the lid open events)
cask "do-not-disturb"

# Microsoft Office stuff can be replaced with LibreOffice
# cask "microsoft-auto-update"
# cask "microsoft-office"
cask "libreoffice"

# Control the brightness of multiple screens
cask "monitorcontrol"
cask "mqttfx"
# The perfect open-source RSS reading tool
cask "netnewswire"
cask "ngrok"
cask "notion"
cask "numi"
cask "obs"
cask "opera"
cask "openemu"
cask "origin"
cask "playonmac"
cask "porting-kit"

# Crypto wallets
cask "electrum"
cask "monero-wallet"

# Request sending Apps
cask "postman"
# cask "insomnia"

cask "prismatik"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "quik"
cask "raycast"
cask "raspberry-pi-imager"
# Replaced by Raycast's built-in emoji searcher
# cask "rocket"
cask "shottr"
cask "skype"
cask "slack"
cask "steam"
cask "stats"

# DB manupulation/browsing tools
cask "dbeaver-community"
# Nice UI, but is proprietory and paid
# cask "tableplus"

# Editors
cask "visual-studio-code"
mas "Xcode", id: 497799835

# Difftool, not needed anymore due to NVIM and VSCode
# cask "ksdiff"

cask "tunnelblick"
# Desktop widgets
cask "ubersicht"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "vk-messenger"
cask "vlc"
cask "webpquicklook"
cask "whatsapp"
cask "wireshark"
cask "wkhtmltopdf"
cask "yandex"
cask "yandex-music-unofficial"
cask "zeplin"

cask "cryptomator"
cask "veracrypt"
mas "Bitwarden", id: 1352778147
# cask "authy" # Superseeded by the KeePass
cask "keepassxc"

# Yubikey tools
cask "yubico-yubikey-manager"
cask "yubico-yubikey-personalization-gui"
cask "yubico-yubikey-piv-manager"

# GnuPG & friends
brew "gnupg"
brew "pinentry-mac"

# OpenPGP key archivation to paper / unarchivation from it
# https://www.jabberwocky.com/software/paperkey
# https://wiki.archlinux.org/title/Paperkey
brew "paperkey"
brew "qrencode"
brew "zbar"

# Very nice app, but does not support GPG. Apple Mail + GPG plugin is enough
# mas "Spark", id: 1176895641
# One of the best apps in terms of extensibility and functional + has GPG support
# cask "thunderbird"
# Apple Mail plugin for OpenPGP
cask "free-gpgmail"
cask "mailtrackerblocker"

# Shells & shell-related
brew "bash"
brew "checkbashisms"
brew "shellcheck"
brew "shfmt"
brew "zsh"
brew "zsh-history-substring-search"

# Does not show the event details in the tray
# cask "itsycal"
# Cron is nice, but not really different from Apple Calendar
# cask "cron"
# MeetingBar + Apple Calendar combo works the best
cask "meetingbar"

# cask "joplin" # Superseded by Obsidian
cask "obsidian"

# cask "hiddenbar" # Superseded by bartender
cask "bartender"

# Cloud mount/manipulation tools.
# Superseded by mountain duck, but it does not really
# play nicely with Cryptomator vaults natively, so still
# using the standalone Cryptomator app
# cask "google-drive"
cask "yandex-disk"
# iOS does not work well with background syncs, so syncthing is not really convenient to use
# cask "syncthing"
brew "rclone"
cask "kapitainsky-rclone-browser"
cask "mountain-duck"
# Creates a TmpFS disk in RAM on login
cask "tmpdisk"

# Best todo list tracker
cask "ticktick"
# cask "todoist"

mas "Amphetamine", id: 937984704
mas "Dropover", id: 1355679052
mas "GIPHY CAPTURE", id: 668208984
mas "Keynote", id: 409183694
mas "Notchmeister", id: 1599169747
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Tailscale", id: 1475387142
mas "Telegram", id: 747648890
