# Some instructions of how to interact with the Brewfile
# https://gist.github.com/ChristopherA/a579274536aab36ea9966f301ff14f3f
# 
# A big list of comonly used brew packages
# https://github.com/joelparkerhenderson/brewfile/blob/master/Brewfile
#
# Brew always calls tap on the packages that are not in the core, so
# having an explicit tap does not add any overhead

# TODO: migrate it all on Nix and leave here only what cannot be installed through Nix

# No need to tap homebrew/core and homebrew/cask anymore,
# unless developing a formulae:
# https://brew.sh/2023/02/16/homebrew-4.0.0/
tap "homebrew/bundle"

brew "awscli"
brew "axel"
brew "cheat"
brew "clang-format"
brew "coreutils"

# wget is not present on every OS, so better stick to curl
# brew "wget"
brew "curl"

# Unified tools version manager (nodejs, python, etc.)
brew "asdf"
# brew "direnv"
# brew "fnm"
# brew "pipenv"
# brew "pyenv"

brew "eksctl"
# Reads/modifies EXIF and video metadata
brew "exiftool"
brew "ffmpeg"
brew "fzf"
brew "gawk"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "git-absorb"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "gotop"
brew "grc"

# Cloud CLIs
# Heroku - in case we want to deploy using the heroku-cli
# brew "heroku/brew/heroku"
brew "doctl"

brew "htop"
brew "i2p"
brew "imagemagick"
# ftp, telnet, etc.
brew "inetutils"
brew "jc"
# Converts output of unix commands to JSON
# https://github.com/kellyjonbrazil/jc
brew "jq"
brew "jupyterlab"
brew "lazygit"
# VimTeX uses latexmk as the default compiler backend
# latexmk is getting bundled with texlive
# https://mg.readthedocs.io/latexmk.html#installation
brew "texlive"
# Backend processor for BibLaTeX
brew "biber"
# To be able to send notifications from the scripts
# Required for some items in ../../../bin/.local/bin/
brew "terminal-notifier"

# PostgreSQl
brew "libpq"
brew "postgresql"

brew "lua"
brew "luarocks" # lua package manager
brew "luajit-openresty"
brew "make"
brew "mas"
brew "midnight-commander"
brew "mosh"
brew "mpv"
# Replaces a built-in MacOS version of ncurses for the sake of having an up-to-date terminfo
brew "ncurses"

# neofetch got deprecated
# brew "neofetch"

brew "neovim"
# From checkhealth: vimtex#view#inverse_search is better if pstree is available
brew "pstree"
brew "findutils"
# brew "ranger" # File browser, superseded by nvim
# Is required to fix the ranger's freezes
# https://github.com/ranger/ranger/issues/1787#issuecomment-691528698https://github.com/ranger/ranger/issues/1787#issuecomment-691528698
# brew "highlight"

brew "nginx"
brew "onefetch"
brew "openjdk"
# Same as pinentry for GPG, but for SSH
brew "theseal/ssh-askpass/ssh-askpass"
brew "perl"
brew "php"

# Fixes the issue with the missing Tkinter module during Python 3.11 build
# https://stackoverflow.com/a/67465708
brew "python-tk"

# Mainly for PostgreSQl 
brew "openssl"
# Make SSH up to date
# Commented out because this one does not support the --apple-use-keychain flag
# brew "openssh"

# GNU utility to edit the command lines as they are typed in.
# Was extracted from bash, now used pretty much everywhere the prompt
# exists. zsh uses zle instead.
# $XDG_CONFIG_HOME/readline/inputrc is the config file.
# https://www.youtube.com/watch?v=MxRTh8wlmJk
# https://tiswww.case.edu/php/chet/readline/rltop.html
brew "readline"

# Grep AST
brew "ast-grep"
brew "ripgrep"

brew "ruby"
brew "sox"
# As education have finished
# brew "spin"
brew "stow"
# Linter for lua (used by nvim)
brew "stylua"
brew "svgo"

# XDG Base Directory spec-compliant Rust tldr implementation
brew "tealdeer"
# brew "tldr"

brew "tmux"
brew "tmuxinator"

# Using it instead of the rm for soft-deletion
brew "trash"
brew "tree"
brew "ykman"
brew "yq"

# Cat alternative
brew "bat"
brew "bat-extras"

# PDR and other docs reader
tap "zegervdv/zathura"
brew "zegervdv/zathura/zathura"
brew "zegervdv/zathura/zathura-djvu"
brew "zegervdv/zathura/zathura-pdf-poppler"

cask "1password"
cask "adobe-acrobat-reader"
cask "alt-tab"

# As no Android devices at the moment
# cask "android-file-transfer"
# cask "android-platform-tools"
# KDE Connect for Mac (pairs MacOS, iOS, Android and Linux together)
cask "soduto"

cask "anydesk"
cask "appcleaner"

# Hold the command key a bit longer to get a list of all active shortcuts of the current application
# Got discontinued, so migrated to another one
# cask "cheatsheet"
cask "keyclu"

cask "crossover"
cask "dash"
cask "deluge"
cask "devtoys"
cask "discord"
cask "dotnet-sdk"
cask "djview"

# Do not using the formulae as cask contains both CLI and GUI
cask "docker"
# Orbstack was useful for the ARM Macs before many containers supported ARM, now obsolete
# cask "orbstack"
brew "lazydocker"

# Nicest diagramming/drawing app
cask "drawio"
cask "element"
cask "fbreader"
cask "flash-npapi"
# Flipper Zero app
cask "qflipper"

# Nerd fonts for the icons within terminal
# Patched nerd fonts for the icons within terminal
# Not yet possible to get rid of those, because Alacritty does not support
# fallback fonts yet: https://github.com/alacritty/alacritty/issues/957
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-sauce-code-pro-nerd-font"
cask "font-martian-mono-nerd-font"
# To be able to use non-patched fonts, it is possible to use original with a
# patched icon-only font: https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font
cask "font-fira-code" # Perfect
cask "font-jetbrains-mono" # Perfect, but does not have "---" ligature (nvim)
cask "font-source-code-pro"
cask "font-symbols-only-nerd-font"
# Does not have ligatures + is not patched with nerd-fonts
# cask "font-input"
# Does not have ligatures
# cask "font-intel-one-mono"
# Very readable, but too big parenthesis and lack of "---" ligature
# cask "font-juliamono"
# Free font builder
cask "birdfont"

# E-Book library
cask "calibre"
# Scientific papers library
# cask "mendeley" # Got deprecated
cask "mendeley-reference-manager"

cask "inkscape"
cask "gimp"

# Grammar checking tools
cask "languagetool"
# cask "grammarly" # Deprecated in favour of web app

cask "hazeover"
cask "keycastr"

# Best archiving tool so far
cask "keka"
# Required to make Keka default archiving program
cask "kekaexternalhelper"
# Is payed + has annoying paywall notifications
# cask "betterzip"

# Window managers
# cask "amethyst" # superseded by yabai & skhd + is a bit more buggy than the latter combo
# The following two work together, one for window management, another for keyboard shortcuts
# Each reinstall requires to remove explicitly apps from the a11y settings and add on ask
tap "koekeishiya/formulae"
brew "koekeishiya/formulae/yabai"
# --with-logging adds log files to the plist
brew "koekeishiya/formulae/skhd", args: ["with-logging"]
cask "karabiner-elements"

# Browsers
cask "chromium"
cask "google-chrome"
cask "microsoft-edge"
cask "firefox"
cask "brave-browser"
cask "tor-browser"
cask "yandex"
# Browsers managers
mas "Velja", id: 1607635845
# cask "browserosaurus"
cask "browserstacklocal"

# Sindre Sorhus apps (https://sindresorhus.com/)
mas "Hyperduck", id: 2145267525

# The only feature-rich terminal emulator for MacOS with blur background/ligatures is iTerm2
cask "ghostty"
# cask "iterm2"
# cask "alacritty"
# cask "kitty"

# The best launchd/ctl inspector/editor
cask "launchcontrol"
# A convenient wrapper around launchctl
# brew "lunchy"

# VPNs
cask "cloudflare-warp"
cask "tunnelblick"
brew "openvpn"

# Objective-See (objective-see.org) security-related apps
# Nice and open-source outbound firewall
cask "lulu"
# Prevents "evil-maid" attacks (listens to the lid open events)
# cask "do-not-disturb" # Unfortunately, got deprecated
# Sends notifications when the video device becomes active
cask "oversight"

# Microsoft Office stuff can be replaced with LibreOffice
# cask "microsoft-auto-update"
# cask "microsoft-office"
cask "libreoffice"

# Control the brightness of multiple screens
cask "monitorcontrol"
cask "mqttfx"
# The perfect open-source RSS reading tool
cask "netnewswire"
cask "ngrok"
cask "numi"
cask "obs"
cask "opera"
cask "openemu"
cask "porting-kit"

# Gaming apps
cask "steam"
cask "epic-games"
cask "gog-galaxy"
cask "ea" # Successor of `cask "origin"`
cask "playonmac"

# Crypto wallets
cask "electrum"
cask "monero-wallet"

# Request sending Apps
cask "postman"
# cask "insomnia"

# Apple QuickLook plugins
# `ql` is an alias for QuickLook
# cask "qlimagesize" # Got deprecated
cask "avifquicklook"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"

cask "prismatik"
cask "quik"
cask "raycast"
cask "raspberry-pi-imager"
# Replaced by Raycast's built-in emoji searcher
# cask "rocket"
cask "shottr"

# Skype is superseded by Teams
# cask "skype"
cask "microsoft-teams"
cask "slack"
cask "vk-messenger"
cask "whatsapp"

# DB manupulation/browsing tools
cask "dbeaver-community"
# Open-source data exploration tool
cask "datasette"
# Nice UI, but is proprietory and paid
# cask "tableplus"

# Editors
cask "visual-studio-code"
cask "visual-studio-code@insiders"
cask "zed"
mas "Xcode", id: 497799835

# Difftool, not needed anymore due to NVIM and VSCode
# cask "ksdiff"

# Desktop widgets
cask "ubersicht"
cask "stats"

# cask "vlc"
cask "iina"

cask "webpquicklook"
cask "wireshark"

brew "qemu"
cask "vmware-fusion" # Just-open Windows machine
cask "virtualbox"
# This cask got deprecated https://github.com/orgs/Homebrew/discussions/4263
# cask "virtualbox-extension-pack"

cask "yandex-music"
# cask "yandex-music-unofficial" # Now Mac app is official
# Allows to granularly control the volume on the level of apps
cask "background-music"

cask "figma"
cask "zeplin"

# FUSE implementations are needed for the Cryptomator mounts
cask "fuse-t"
# Deprecated one since macOS 12.3 (https://docs.cryptomator.org/en/1.7/desktop/volume-type/#macfuse)
# cask "macfuse"

# Password managers
mas "Bitwarden", id: 1352778147
brew "bitwarden-cli"
# cask "authy" # Superseeded by the KeePass
cask "keepassxc"

# Yubikey tools
brew "pam-u2f"
cask "yubico-yubikey-manager"
cask "yubico-yubikey-personalization-gui"
cask "yubico-yubikey-piv-manager"

# GnuPG & friends
brew "gnupg"
brew "pinentry-mac"

# GPG modern analogue, can use SSH key for encryption
# https://github.com/C2SP/C2SP/blob/main/age.md
# Rust implementation
tap "str4d.xyz/rage"
brew "rage"
# brew "age"

# OpenPGP key archivation to paper / unarchivation from it
# https://www.jabberwocky.com/software/paperkey
# https://wiki.archlinux.org/title/Paperkey
brew "paperkey"
brew "qrencode"
brew "zbar"

# Very nice app, but does not support GPG. Apple Mail + GPG plugin is enough
# mas "Spark", id: 1176895641
# One of the best apps in terms of extensibility and functional + has GPG support
# cask "thunderbird"
# Apple Mail plugin for OpenPGP
cask "free-gpgmail"
cask "mailtrackerblocker"

# Shells & shell-related
brew "bash"
brew "atuin"
tap "homebrew/command-not-found"
# Fancy cd using frecency, agkozak/zsh-z (rupa/z) alternative
brew "zoxide"
brew "checkbashisms"
tap "kaplanelad/tap"
brew "kaplanelad/tap/shellfirm"
brew "shellcheck"
brew "shfmt"
# ZSH-related
brew "zsh"
brew "starship"
# brew "antigen" # very slow and is not really maintained
# brew "zplug" # slow as well

# Does not show the event details in the tray
# cask "itsycal"
# Cron is nice, but not really different from Apple Calendar
# cask "cron"
# MeetingBar + Apple Calendar combo works the best
cask "meetingbar"

# linear.app
cask "linear-linear"
# cask "joplin" # Superseded by Obsidian
cask "obsidian"
cask "notion"

# Both are superseded by ice for different reasons
# cask "hiddenbar"
# cask "bartender"
cask "jordanbaird-ice"

# Cloud mount/manipulation tools.
cask "google-drive"
cask "yandex-disk"
# iOS does not work well with background syncs, so syncthing is not really convenient to use
# cask "syncthing"
brew "rclone"
# Backup/sync tools
brew "rsync"
brew "lsyncd"
# Nice backup tool
brew "restic"
cask "duplicati"
# Got unsupported, the alternative is `rclone rcd --rc-web-gui`
# cask "kapitainsky-rclone-browser"
cask "mountain-duck"
# Creates a TmpFS disk in RAM on login
cask "tmpdisk"
brew "testdisk"
cask "cryptomator"
cask "veracrypt"

# Best todo list tracker
cask "ticktick"
# cask "todoist"

mas "Amphetamine", id: 937984704
mas "Dropover", id: 1355679052
mas "GIPHY CAPTURE", id: 668208984
mas "Keynote", id: 409183694
mas "Notchmeister", id: 1599169747
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Tailscale", id: 1475387142
mas "Telegram", id: 747648890
