[cursor]
style = { blinking = "Never", shape = "Block" }
unfocused_hollow = true

[font]
size = 12.0

[window]
blur = true
decorations = "transparent"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 10
y = 30

[general]
import = [
    "/Users/mvshmakov/.config/alacritty/alacritty-theme/themes/nord.toml",
]
