[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.footer]
background = "#434c5e"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[schemes.default.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[schemes.nord.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[schemes.nord.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[schemes.nord.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[schemes.nord.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[schemes.nord.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[schemes.nord.search.footer]
background = "#434c5e"
foreground = "#d8dee9"

[schemes.nord.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[schemes.nord.selection]
background = "#4c566a"
text = "CellForeground"

[schemes.nord.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[schemes.one_dark.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[schemes.one_dark.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[schemes.one_dark.primary]
background = "#282c34"
foreground = "#abb2bf"

[schemes.one_darker.bright]
black = "#4C566A"
blue = "#5e81ac"
cyan = "#88c0d0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#bf616a"
white = "#abb2bf"
yellow = "#D7BA7D"

[schemes.one_darker.normal]
black = "#4C566A"
blue = "#5e81ac"
cyan = "#88c0d0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#bf616a"
white = "#abb2bf"
yellow = "#D7BA7D"

[schemes.one_darker.primary]
background = "#1f2227"
foreground = "#abb2bf"
