[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

# Menlo font

# [font.bold]
# family = "Menlo"
# style = "Bold"

# [font.bold_italic]
# family = "Menlo"
# style = "Bold Italic"

# [font.italic]
# family = "Menlo"
# style = "Italic"

# [font.normal]
# family = "Menlo"
# style = "Regular"

# Iosevka Nerd Font

# [font.bold]
# family = "Iosevka Nerd Font"
# style = "Bold"

# [font.bold_italic]
# family = "Iosevka Nerd Font"
# style = "Bold Italic"

# [font.italic]
# family = "Iosevka Nerd Font"
# style = "Italic"

# [font.normal]
# family = "Iosevka Nerd Font"
# style = "Regular"
