require "mvshmakov.options"
require "mvshmakov.keymaps"
require "mvshmakov.plugins"
require "mvshmakov.autocommands"
require "mvshmakov.colorscheme"
require "mvshmakov.cmp"
require "mvshmakov.telescope"
require "mvshmakov.treesitter"
-- require "mvshmakov.autopairs"
-- require "mvshmakov.comment"
require "mvshmakov.gitsigns"
-- require "mvshmakov.nvim-tree"
-- require "mvshmakov.bufferline"
require "mvshmakov.lualine"
require "mvshmakov.toggleterm"
-- require "mvshmakov.project"
-- require "mvshmakov.impatient"
-- require "mvshmakov.illuminate"
-- require "mvshmakov.indentline"
-- require "mvshmakov.alpha"
require "mvshmakov.lsp"
-- require "mvshmakov.dap"
