code --install-extension akamud.vscode-theme-onedark
code --install-extension blairleduc.touch-bar-display
code --install-extension bradlc.vscode-tailwindcss
code --install-extension christian-kohler.npm-intellisense
code --install-extension cssho.vscode-svgviewer
code --install-extension deibit.devdocs
code --install-extension dsvictor94.promela
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension flowtype.flow-for-vscode
code --install-extension GitHub.vscode-pull-request-github
code --install-extension leizongmin.node-module-intellisense
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension quicktype.quicktype
code --install-extension shakram02.bash-beautify
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-russian
code --install-extension TabNine.tabnine-vscode
code --install-extension techer.open-in-browser
code --install-extension vscode-ext.sync-rsync
code --install-extension vscode-icons-team.vscode-icons
code --install-extension xyz.local-history
code --install-extension Zeplin.zeplin
code --install-extension Zignd.html-css-class-completion
