#!/usr/bin/env sh
#
# To list all aliases in shell type `alias`. Big portion of the list is from oh-my-zsh:
# https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/common-aliases/common-aliases.plugin.zsh#LL26C20-L26C20

## Colorization ##

# It is still required to colorize the tools explicitly, because CLICOLOR
# is only for the MacOS/BSD: https://unix.stackexchange.com/a/2904
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

## Safety ##

# Forcing the tools to ask for the deletion confirmation
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

## CLI shortcuts ##

alias ..='cd ..'
alias ll='ls -lAFh' # Long list, show almost all, show type, human readable

alias zshrc='${=EDITOR} ${ZDOTDIR:-$HOME}/.zshrc' # Quick access to the .zshrc file

## General ##

# Browsers
alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'
alias chromium='/Applications/Chromium.app/Contents/MacOS/Chromium'
alias yabro='/Applications/Yandex.app/Contents/MacOS/Yandex'
alias firefox='/Applications/Firefox.app/Contents/MacOS/Firefox'
alias safari='/Applications/Safari.app/Contents/MacOS/Safari'
alias opera='/Applications/Opera.app/Contents/MacOS/Opera'

# Reload the shell (i.e. invoke as a login shell)
alias reload='exec $SHELL -l'

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Recursively delete `.DS_Store` files
alias clean_ds="find . -type f -name '*.DS_Store' -ls -delete"

alias cp_pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"
alias cp_test_pubkey="more ~/.ssh/id_rsa-test.pub | pbcopy | echo '=> Public key copied to pasteboard.'"

# Merge PDF files, preserving symbolic links
# Usage: `mergepdf input{1,2,3}.pdf` or `mergepdf_local` for PDFs in folder merge
alias mergepdf='gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=_merged.pdf'
alias mergepdf_local='ls -a | grep .pdf$ | xargs gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=_merged.pdf'

# Locks the screen
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# CPU/Memory usage
alias topmem='top -stats "pid,command,mem,cpu" -o mem'
alias topcpu='top -stats "pid,command,cpu,mem" -o cpu'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# macOS has no `md5sum`, so use `md5` as a fallback
command -v md5sum >/dev/null || alias md5sum="md5"
# macOS has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum >/dev/null || alias sha1sum="shasum"

# XCode aliases
alias ios="open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app"

# tmux aliases
alias tmuxify="tmux -CC attach || tmux -CC new"

# TTL for free network sharing, 65 - "on", 64 - "off"
alias ttl_64="sudo sysctl -w net.inet.ip.ttl=64"
alias ttl_65="sudo sysctl -w net.inet.ip.ttl=65"

# Shorthand for `tree` with hidden files and color enabled, ignoring
# the `.git` and `node_modules` directories, listing directories first.
# The output gets piped into `less` with options to preserve color and
# line numbers, unless the output is small enough for one screen.
alias tree="tree -aC -I '.git|node_modules' --dirsfirst "$@" | less -FRNX"
