#!/usr/bin/env sh
#
# yabai configuration file
# Mosty taken from https://www.josean.com/posts/yabai-setup

# Default layout (can be bsp, stack or float)
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Add padding od 12px
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# Center mouse on window with focus
yabai -m config mouse_follows_focus on

# Modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# Set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# Set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# When window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action swap

# Disable specific apps from being managed with yabai
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^LaunchControl$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
