#!/usr/bin/env sh
#
# yabai configuration file
# Mosty taken from https://www.josean.com/posts/yabai-setup

# Default layout (can be bsp, stack or float)
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Add padding od 12px
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# Center mouse on window with focus
yabai -m config mouse_follows_focus on

# Modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# Set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# Set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# When window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action swap

# Disable specific apps from being managed with yabai
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^LaunchControl$" manage=off
yabai -m rule --add app="^Karabiner-(Elements|EventViewer)$" manage=off
yabai -m rule --add app="^System (Information|Preferences|Settings)$" manage=off
# Do not manage TouchID prompts because the Firefox Bitwarden extension closes
# on window resize caused by yabai. The app name was found with Karabiner-EventViewer
# as `yabai -m query --windows` does not list it
yabai -m rule --add app="^coreautha$" manage=off

yabai -m rule --add title="^(Picture in Picture|Picture-in-Picture)$" manage=off
