on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

name: "Making sure the codebase is perfect"
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          # TODO: get rid of _archive ignore
          ignore_paths: _archive
          # ShellCheck doesn't support zsh yet
          # https://github.com/koalaman/shellcheck/issues/809
          ignore_names: *.zsh
