on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

name: "Making sure the codebase is perfect"
jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install linters
        run: sudo apt-get update && sudo apt-get install -y shellcheck shfmt
      - name: Run lint checks
        run: make lint
